### PR TITLE
Update Themes.php

### PR DESCRIPTION
**Pull request by SolStis86**
Replaced FileViewFinder::setPaths with new logic for updated method addLocation

### CODE REVIEW

**Comment by igaster** [comment]
Hmm I think that the theme paths are already being prepended... I will test it localy to confirm...

**Comment by SolStis86** [comment]
The reason for this is that im getting an undefined method exception for FileViewFinder::setPaths when updating to laravel 5.5...

**Comment by igaster** [comment]
This is strange, this function is defined [here](https://github.com/igaster/laravel-theme/blob/master/src/themeViewFinder.php#L116). This class is loaded by the `themeServiceProvider.php` which in turn is defined in `app.php`.

L5.5 should auto resolve package service providers, but just in case you could try to add it manualy on the in the `providers` array... Beware that you should add it at the `Package Service Providers...` area, since the order of the service providers could matter.

**Comment by SolStis86** [comment]
It looks like the registration of 'view.finder' isnt overriding the FileViewFinder for some reason

**Comment by igaster** [comment]
There is an issue when composer update will fail to execute `artisan optimize` when you are upgrading. Try to manually execute `artisan optimize` and test again.

Also if you couldshare your `app.php` it might help.
You can sent them directly to my email if you want: igasteratos@gmail.com

Sorry if I am making it a trouble for you...

**Pull request closed without merging**
